server:
  port: 8001
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://eureka1:7001/eureka/,http://eureka2:7002/eureka/,http://eureka3:7003/eureka/

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: cn.itcat.springcloud.entity
  mapper-locations:
  - classpath:mybatis/mapper/*.xml
  
spring:
  application:
    name: provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/springcloud
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                               #最小连接数
      initial-size: 5                                           #初始化连接数
      max-idle: 5                                               #最大连接数