server:
  port: 9527
  
spring:
  application:
    name: microservicecloud-zuul
    
zuul:
  prefix: /itcast                                                   #前缀
  ignored-services: '*'                                        #忽略原真实应用名
  routes:
    dept:
      path: /dept/**                                              #访问路径
      service-id: provider                                        #应用名
  
eureka:
  instance:
    instance-id: zuul
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka1:7001/eureka/,http://eureka2:7002/eureka/,http://eureka3:7003/eureka/
